[package]
name = "cogo-http"
version = "0.1.0"
edition = "2021"
description = "A modern HTTP library."
readme = "README.md"

authors = ["zhuxiujia <zhuxiujia@qq.com>",
    "Sean McArthur <sean.monstar@gmail.com>",
    "Jonathan Reem <jonathan.reem@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
include = [
    "Cargo.toml",
    "LICENSE",
    "src/**/*"
]

[features]
default = ["runtime_cogo"]
runtime_thread = []
runtime_cogo = ["cogo"]
nightly = []

[dependencies]
base64 = "0.9.0"
httparse = "1.0"
language-tags = "0.2"
log = "0.3"
mime = "0.2"
num_cpus = "1.0"
time = "0.1"
traitobject = "0.1"
typeable = "0.1"
unicase = "1.0"
url = "1.0"
cogo = {version = "0.1", optional = true }

crossbeam = "0.8"
crossbeam-channel = "0.5"

[dev-dependencies]
env_logger = "0.4"

