[package]
name = "example"
version = "0.0.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"
publish = false
exclude = ["examples/*"]


[dependencies]
mco="*"
mco-http = { path = "../" }
mco-http-rustls = {path = "../mco-http-rustls"}
fast_log = "1.6"
serde = "1"
serde_json = "1"
cdbc = "0.1"
cdbc-sqlite = "0.1"
#captcha
lodepng = "~3.5.2"
captcha = "0.0.8"
jsonwebtoken = "8"
httparse = "1"
log = "0.4.20"

#tls
rustls = "0.20"
rustls-pemfile = "0.2.1"

[[bin]]
name = "http_client"
path = "src/http_client.rs"
[[bin]]
name = "https_client"
path = "src/https_client.rs"
[[bin]]
name = "http"
path = "src/http.rs"
[[bin]]
name = "https"
path = "src/https.rs"
[[bin]]
name = "server_database"
path = "src/server_database.rs"
[[bin]]
name = "server_download"
path = "src/server_download.rs"
[[bin]]
name = "server_form_data"
path = "src/server_form_data.rs"
[[bin]]
name = "server_json"
path = "src/server_json.rs"
[[bin]]
name = "server_jwt_token"
path = "src/server_jwt_token.rs"
[[bin]]
name = "server_mock"
path = "src/server_mock.rs"
[[bin]]
name = "server_path"
path = "src/server_path.rs"
[[bin]]
name = "server_query"
path = "src/server_query.rs"
[[bin]]
name = "server_router"
path = "src/server_router.rs"
[[bin]]
name = "server_router_container"
path = "src/server_router_container.rs"
[[bin]]
name = "server_router_middleware"
path = "src/server_router_middleware.rs"
[[bin]]
name = "server_upload"
path = "src/server_upload.rs"
[profile.release]
lto = true
opt-level = 3
codegen-units = 1