[package]
name = "example"
version = "0.0.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"
publish = false
exclude = ["examples/*"]


[dependencies]
mco={version="*",path="../../mco"}
mco-http = { path = "../" }
mco-http-rustls = {path = "../mco-http-rustls"}
fast_log = "1.6"
serde = "1"
serde_json = "1"
cdbc = "0.1"
cdbc-sqlite = "0.1"
#captcha
lodepng = "~3.5.2"
captcha = "0.0.8"
jsonwebtoken = "8"
httparse = "1"
log = "0.4.20"

#tls
rustls = "0.20"
rustls-pemfile = "0.2.1"

tungstenite = "0.21"
url = "2.1"

[[bin]]
name = "http_client"
path = "src/http_client.rs"
[[bin]]
name = "https_client"
path = "src/https_client.rs"
[[bin]]
name = "http_server"
path = "src/http_server.rs"
[[bin]]
name = "https_server"
path = "src/https_server.rs"
[[bin]]
name = "http_server_database"
path = "src/http_server_database.rs"
[[bin]]
name = "http_server_download"
path = "src/http_server_download.rs"
[[bin]]
name = "http_server_form_data"
path = "src/http_server_form_data.rs"
[[bin]]
name = "http_server_json"
path = "src/http_server_json.rs"
[[bin]]
name = "http_server_jwt_token"
path = "src/http_server_jwt_token.rs"
[[bin]]
name = "http_server_mock"
path = "src/http_server_mock.rs"
[[bin]]
name = "http_server_path"
path = "src/http_server_path.rs"
[[bin]]
name = "http_server_query"
path = "src/http_server_query.rs"
[[bin]]
name = "http_server_router"
path = "src/http_server_router.rs"
[[bin]]
name = "http_server_router_container"
path = "src/http_server_router_container.rs"
[[bin]]
name = "http_server_router_middleware"
path = "src/http_server_router_middleware.rs"
[[bin]]
name = "http_server_upload"
path = "src/http_server_upload.rs"
[[bin]]
name = "http_websocket_server"
path = "src/http_websocket_server.rs"
[[bin]]
name = "http_websocket_client"
path = "src/http_websocket_client.rs"


[profile.release]
lto = true
opt-level = 3
codegen-units = 1